find-perl can now search Perl system directories.
Converted the script to Bash to use arrays; it's simpler. For now.
For zsh only environment either, it should work with old bash versions.
I might add zsh support later or convert it to POSIX once I have some time.

diff --git a/bin/find-perl b/bin/find-perl
--- a/bin/find-perl
+++ b/bin/find-perl
@@ -1,10 +1,10 @@
-#!/bin/sh
+#!/usr/bin/env bash
 # SH FILE: find-perl
 #
 # Purpose   : Find all Perl files in specified directory tree.
 # Created   : Tuesday, October  8 2024.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2025-01-16 23:46:52 EST, updated by Pierre Rouleau>
+# Time-stamp: <2025-01-17 19:00:53 EST, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 # Module Description
 # ------------------
@@ -36,11 +36,16 @@ find-perl: Find and print the name of every Perl file found in directory tree.
 
   • Print this help information.
 
- Usage: find-perl [DIR, ...]
+ Usage: find-perl {[-p|--with-system-perl] |[-P|--only-system-perl] [DIR, ...]
 
   • Search and print name of Perl files found in specified directories.
     - If DIR is not specified, search in the current working directory.
-  • This also finds script files that uses the /usr/bin/perl shebang line.
+  • If -p or --with-system-perl:  search the directories that Perl
+    identifies in its @INC variable as well as the other directories.
+  • if the -P or --only-system-perl option is identified then ONLY
+    search the the directories that Perl identifies in its @INC variable.
+    When that option is included the DIR arguments are not allowed.
+  • This also finds script files that uses a Perl shebang line.
   • The first list is for scripts, then the pure Perl files.
 
 "
@@ -56,7 +61,32 @@ if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     exit 0
 fi
 
+search_other_directories=true
+search_perl_system_directories=false
+if [ -n "$1" ]; then
+    if [ "$1" = "-p" ] || [ "$1" = "--with-system-perl" ]; then
+        search_perl_system_directories=true
+        shift
+    elif [ "$1" = "-P" ] || [ "$1" = "--only-system-perl" ]; then
+        search_perl_system_directories=true
+        search_other_directories=false
+        shift
+        if [ -n "$1" ]; then
+            printf -- "*** find-perl ERROR: no extra DIR with --only-system-perl.\n"
+            printf -- "    Use 'find-perl -h' to get more information.\n"
+            exit 1
+        fi
+    else
+        if [ ! -d "$1" ]; then
+            printf -- "*** find-perl ERROR: not a valid directory: %s\n" "$1"
+            printf -- "    Use 'find-perl -h' to get more information.\n"
+            exit 1
+        fi
+    fi
+fi
 
+# --
+# Identify the command to use.
 
 if [ -x "$(command -v fdfind)" ]; then
     search_with='fd'
@@ -87,35 +117,66 @@ fi
 # stderr redirected to /dev/null to hide warnings trying to access
 # non-accessible directories.
 
-# First search for shell scripts that use Perl.
+# --
+# Identify the directories to process
+
+declare -a searched_directories
+searched_directories=()
+if [ "$search_other_directories" = "true" ]; then
+    if [ -z "$1" ]; then
+        searched_directories=( "$(pwd)" )
+    else
+        searched_directories=( "$@" )
+    fi
+fi
+
+if [ "$search_perl_system_directories" = "true" ]; then
+    # Add any Perl system directory that exist and is not a child of another
+    for dname in $(perl -e 'print join("\n", @INC), "\n";' | sort | uniq); do
+        found=false
+        if [ -d "$dname" ] ; then
+            dpath="$(realpath "${dname}")"
+            for d in "${searched_directories[@]}"; do
+                #shellcheck disable=SC2076 ## match literally the expansion of $d
+                if [[ "$dname" =~ "$d" ]]; then
+                    found=true
+                    # printf -- "subdir: %s\n" $dname
+                    break
+                fi
+            done
+            if [ "$found" = "false" ]; then
+                searched_directories+=("$dpath")
+            fi
+        fi
+    done
+fi
+
+# --
+# Search for shell scripts that use Perl: use rg if available, otherwise use grep.
+#
 # - Exclude perltidy files, Emacs backup and buffers files.
 if [ -x "$(command -v rg)" ]; then
-    if [ -z "$1" ]; then
-        rg -g !'*.tdy' -g !'*~' -g !'*#' -Nl "^#! .+/perl" "$(realpath .)" 2> /dev/null
-    else
-        for dname in "$@"; do
-            rg -g !'*.tdy' -g !'*~' -g !'*#' -Nl "^#! .+/perl" "$(realpath "$dname")" 2> /dev/null
-        done
-    fi
+    for dname in "${searched_directories[@]}"; do
+        rg -g !'*.tdy' -g !'*~' -g !'*#' -Nl "^#! .+/perl" "$(realpath "$dname")" 2> /dev/null
+    done
 else
     # rg is not available; use recursive grep:
     # -l : just list file name
     # -r: recursive
     # -E: extended regular expressions
     # As it might iterate over files that have restricted access: wipe error messages
-    if [ -z "$1" ]; then
-        grep -l --exclude '*.tdy' --exclude '*~' --exclude '*#'  -r -E "^#! .+/perl" "$(realpath .)" 2> /dev/null
-    else
-        for dname in "$@"; do
-            grep -l --exclude '*.tdy' --exclude '*~' --exclude '*#' -E -r "^#! .+/perl" "$(realpath "$dname")" 2> /dev/null
-        done
-    fi
+    for dname in "${searched_directories[@]}"; do
+        grep -l --exclude '*.tdy' --exclude '*~' --exclude '*#' -E -r "^#! .+/perl" "$(realpath "$dname")" 2> /dev/null
+    done
 fi
 
+# --
+# Search the Perl code files. Use fd if available, otherwise use find.
+#
 case "$search_with" in
     find)
         find -L                        \
-             ${find_path_option} "$@"  \
+             "${find_path_option}" "${searched_directories[@]}"  \
              \(  -name "*.p[lm]"       \
              -or -name "*.pl[sx]"      \
              -or -name "*.xs"          \
@@ -142,7 +203,7 @@ case "$search_with" in
                   -e .cgi            \
                   -e .psg            \
                   -e .psgi           \
-                  . "$@" 2> /dev/null
+                  . "${searched_directories[@]}" 2> /dev/null
         ;;
 
     *)
@@ -153,5 +214,5 @@ esac
 
 # ----------------------------------------------------------------------------
 # Local Variables:
-# sh-shell: /bin/sh
+# sh-shell: /bin/bash
 # End:
