Print errors on stderr

diff --git a/bin/iconv-iso8859-utf8 b/bin/iconv-iso8859-utf8
--- a/bin/iconv-iso8859-utf8
+++ b/bin/iconv-iso8859-utf8
@@ -4,7 +4,7 @@
 # Purpose   : Convert a ISO-8859 encoded file to UTF-8.
 # Created   : Monday, September  1 2025.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2025-09-01 20:52:41 EDT, updated by Pierre Rouleau>
+# Time-stamp: <2025-09-01 20:55:33 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 # Description
 # -----------
@@ -76,20 +76,20 @@ elif [ -n "$2" ]; then
 fi
 
 if [ -z "$USRHOME_DIR_TMP" ]; then
-    printf -- "*** iconv-iso8859-utf8 ERROR: USRHOME_DIR_TMP envvar missing.\n"
-    printf -- "        Use --help for more info.\n"
+    >&2 printf -- "*** iconv-iso8859-utf8 ERROR: USRHOME_DIR_TMP envvar missing.\n"
+    >&2 printf -- "        Use --help for more info.\n"
     exit 1
 fi
 if [ ! -d "$USRHOME_DIR_TMP" ];  then
-    printf -- "*** iconv-iso8859-utf8 ERROR: USRHOME_DIR_TMP: not a directory.\n"
-    printf -- "        It's value is: %s\n" "$USRHOME_DIR_TMP"
-    printf -- "        Use --help for more info.\n"
+    >&2 printf -- "*** iconv-iso8859-utf8 ERROR: USRHOME_DIR_TMP: not a directory.\n"
+    >&2 printf -- "        It's value is: %s\n" "$USRHOME_DIR_TMP"
+    >&2 printf -- "        Use --help for more info.\n"
     exit 1
 fi
 if [ ! -e "$1" ]; then
-    printf -- "*** iconv-iso8859-utf8 ERROR: USRHOME_DIR_TMP: invalid file name.\n"
-    printf -- "      You specified: %s\n" "$1"
-    printf -- "      This file does not exist.  Use --help for more info.\n"
+    >&2 printf -- "*** iconv-iso8859-utf8 ERROR: USRHOME_DIR_TMP: invalid file name.\n"
+    >&2 printf -- "      You specified: %s\n" "$1"
+    >&2 printf -- "      This file does not exist.  Use --help for more info.\n"
     exit 1
 fi
 
