Fix: envfor-homebrew and envfor-usrhome prevent double use
Now use the easiest and most reliable way to prevent that the PATH setting
logic is executed more than once via sub-shell or sudo shell execution is to
check if the directory(ies) already exist in PATH.  If they do, skip the logic.

diff --git a/ibin/envfor-homebrew b/ibin/envfor-homebrew
--- a/ibin/envfor-homebrew
+++ b/ibin/envfor-homebrew
@@ -3,7 +3,7 @@
 # Purpose   : Activate use of Homebrew's installed utilities.
 # Created   : Saturday, April  6 2024.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2024-04-06 11:15:58 EDT, updated by Pierre Rouleau>
+# Time-stamp: <2024-04-19 15:45:39 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 # Module Description
 # ------------------
@@ -34,37 +34,47 @@
 # The new way is much more flexible but we have to add the /opt/homebrew directories
 # in the PATH, while this does not have to be done on the old architecture.
 
-usrhome_homebrew_path=\
+if [[ "$USRHOME_TRACE_SHELL_CONFIG" = "1" ]]; then
+echo "-3-: Sourcing \$USRHOME_DIR/ibin/envfor-homebrew"
+fi
+
+
+if !  echo $PATH | grep "/homebrew/" > /dev/null; then
+    # If Homebrew has not already been installed (as seen in PATH)
+    # then install it.  Otherwise skip.
+
+    usrhome_homebrew_path=\
 /opt/homebrew/opt/make/libexec/gnubin:\
 /opt/homebrew/bin:\
 /opt/homebrew/sbin:\
 /opt/homebrew/opt/m4/bin
 
-arch="$(uname -m)"
-case "$arch" in
-    'x86_64' )
-        if [ -d /usr/local/Cellar ]; then
-            if [ "$USRHOME_SHOW_PATH_ACTIVATION" = "1" ]; then
-                echo "- Using Homebrew tools from 'usr/local/Cellar via /usr/local/bin "
+    arch="$(uname -m)"
+    case "$arch" in
+        'x86_64' )
+            if [ -d /usr/local/Cellar ]; then
+                if [ "$USRHOME_SHOW_PATH_ACTIVATION" = "1" ]; then
+                    echo "- Using Homebrew tools from 'usr/local/Cellar via /usr/local/bin "
+                fi
+            else
+                echo "ERROR: Homebrew requested but not found in /usr/local/Cellar"
             fi
-        else
-            echo "ERROR: Homebrew requested but not found in /usr/local/Cellar"
-        fi
-    ;;
-
-    'arm64' | 'aarch64' )
-        if [ -d /opt/homebrew ]; then
-            PATH=${usrhome_homebrew_path}:$PATH
-            if [ "$USRHOME_SHOW_PATH_ACTIVATION" = "1" ]; then
-                echo "- Using Homebrew tools from /opt/homebrew."
-            fi
-        else
-            echo "ERROR: Homebrew requested but not found in /opt/homebrew"
-        fi
         ;;
-    *)
 
-esac
-unset usrhome_homebrew_path
+        'arm64' | 'aarch64' )
+            if [ -d /opt/homebrew ]; then
+                PATH=${usrhome_homebrew_path}:$PATH
+                if [ "$USRHOME_SHOW_PATH_ACTIVATION" = "1" ]; then
+                    echo "- Using Homebrew tools from /opt/homebrew."
+                fi
+            else
+                echo "ERROR: Homebrew requested but not found in /opt/homebrew"
+            fi
+            ;;
+        *)
+
+    esac
+    unset usrhome_homebrew_path
+fi
 
 # ----------------------------------------------------------------------------
diff --git a/ibin/envfor-usrhome b/ibin/envfor-usrhome
--- a/ibin/envfor-usrhome
+++ b/ibin/envfor-usrhome
@@ -3,7 +3,7 @@
 # Purpose   : Add support for USRHOME commands by updating PATH.
 # Created   : Saturday, April  6 2024.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2024-04-11 12:46:40 EDT, updated by Pierre Rouleau>
+# Time-stamp: <2024-04-19 15:44:49 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 # Module Description
 # ------------------
@@ -21,19 +21,30 @@
 # ----
 #
 #
-# For local binaries
-# If a ~/bin exists it may override the URSHOME/bin files.
-if [ "$USRHOME_SHOW_PATH_ACTIVATION" = "1" ]; then
-    echo "- Adding usrhome support."
+
+if [[ "$USRHOME_TRACE_SHELL_CONFIG" = "1" ]]; then
+echo "-3-: Sourcing \$USRHOME_DIR/ibin//envfor-usrhome"
 fi
 
-the_path=$USRHOME_DIR/bin:$PATH
-if [ -d "$HOME/bin" ]; then
-    the_path=$HOME/bin:$the_path
-fi
-export PATH="$the_path"
 
-# cleanup
-unset the_path
+if ! echo $PATH | grep "$USRHOME_DIR" > /dev/null; then
+    # If USRHOME has not already been installed (as seen in PATH),
+    # then install it.  Otherwise skip.
+
+    # For local binaries
+    # If a ~/bin exists it may override the URSHOME/bin files.
+    if [ "$USRHOME_SHOW_PATH_ACTIVATION" = "1" ]; then
+        echo "- Adding usrhome support."
+    fi
+
+    the_path=$USRHOME_DIR/bin:$PATH
+    if [ -d "$HOME/bin" ]; then
+        the_path=$HOME/bin:$the_path
+    fi
+    export PATH="$the_path"
+
+    # cleanup
+    unset the_path
+fi
 
 # ----------------------------------------------------------------------------
