man -s and -S print error if topic not found and exit code is 4
The mechanism used to detect if the man topic was found is
probably not very robust: it checks into the *Message* buffer for the
string stating that the topic was formatted.  Looking for the buffer presence
does not seem to work; looks like the buffer is first created as a potential
output and when fails the buffer is still there.

Ideally Emacs man/woman logic would be updated to be able to report whether
the topic was found. And also probably updated to improve it a little.
But that's a different project.

I'll use the current logic for now, and see if it can be improved later.

diff --git a/ibin/envfor-emacs-for-man b/ibin/envfor-emacs-for-man
--- a/ibin/envfor-emacs-for-man
+++ b/ibin/envfor-emacs-for-man
@@ -3,7 +3,7 @@
 # Purpose   : Set environment to use Emacs as the man reader.
 # Created   : Wednesday, April 17 2024.
 # Author    : Pierre Rouleau <prouleau001@gmail.com>
-# Time-stamp: <2024-04-18 15:33:55 EDT, updated by Pierre Rouleau>
+# Time-stamp: <2024-04-18 17:06:06 EDT, updated by Pierre Rouleau>
 # ----------------------------------------------------------------------------
 # Module Description
 # ------------------
@@ -233,14 +233,26 @@ man()
                 echo "Start emacsclient inside another window and try again."
                 return 1
             else
+                local found
                 case $man_mode in
                     '-s')
-                        emacsclient --eval "(progn (man \"$topic\") (delete-window))" > /dev/null
+                        found=$(emacsclient --eval "(progn (man \"$topic\") \
+                                                           (delete-window) \
+                                                           (with-current-buffer \"*Messages*\" \
+                                                             (end-of-buffer) \
+                                                             (when (search-backward (format \"%s man page formatted\" \"$topic\") nil :noerror) t)))")
                         ;;
                     '-S')
-                        emacsclient --eval "(progn (man \"$topic\"))" > /dev/null
+                        found=$(emacsclient --eval "(progn (man \"$topic\") \
+                                                           (with-current-buffer \"*Messages*\" \
+                                                             (end-of-buffer) \
+                                                             (when (search-backward (format \"%s man page formatted\" \"$topic\") nil :noerror) t)))")
                         ;;
                 esac
+                if [[ "$found" = "nil" ]]; then
+                    printf "ERROR: No man page found for %s\n" "$topic" >&2
+                    return 4
+                fi
             fi
             ;;
 
